### ISSUE TITLE
ValueError: Missing staticfiles manifest entry for 'vendored/moment-timezone-with-data-2012-2022.js'

### ISSUE THREAD

**Issue by fkusei** [pretalx/pretalx-venueless#4]
Whenever i try to access the plugin settings.

Pretalx `2f72af1425d5c3a75b4d10f7b44ff327d407a0f0`, plugin `91de8b7457b0dd9f46bf957e26f53cee06b31cb8`.

Fixed in `main`, maybe we need another release? Or is it advisable to just run `main` in production?

**Comment by rixx** [comment]
That was fixed in 1.3.0 and you're running 1.2.1.

**Comment by fkusei** [comment]
https://github.com/pretalx/pretalx-venueless/tags does not show 1.3.0, so i wasn't aware a new release existed.

**Comment by rixx** [comment]
Yeah, sorry about that. The canonical source for releases is always PyPI (which, FWIW, also comes with an RSS feed etc). I try to remember to push tags, but I am but human etc.

(I know, I could and probably should automate the build process via GitHub actions, but it's so annoying and brittle when it's really just a single command locally – `pydist: aliased to rm -rf dist && python -m build && twine upload dist/*`)
